- name: docker repo
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable'
    state: present
    filename: docker

- name: docker repo signing key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: docker install
  apt:
    name: docker-ce
    state: present
